version: '3.1'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: workWatch
      MYSQL_USER: noe
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: