version: '3.1'
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/app
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: